##### set file directories #####

# links to reference human genome, dbSNP database and temporary file directory
GENOME: "/store/lkemp/publicData/referenceGenome/gatkBundle/GRCh37/ucsc.hg19.fasta"
dbSNP: "/store/lkemp/publicData/dbSNP/ncbi/GRCh37/build151/GATK/All_20180423.vcf.gz"
TEMPDIR: "/store/lkemp/exome_project/tmp/"

##### configuration #####

# rule gatk4_HaplotypeCaller
# mode for emitting reference confidence scores. See https://gatk.broadinstitute.org/hc/en-us/articles/360037225632-HaplotypeCaller
MODE: "GVCF"

# rule trim_galore_pe
# Set additional parameters. See https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md
EXTRA: "--illumina --fastqc -q 20 --cores 4"

##### fixed - don't change #####

# Overall description of the pipeline/workflow
REPORTWORKFLOW: "report/workflow_37.rst"