# Specify the build of reference human genome used (either GRCh37 or GRCh38)
BUILD: "GRCh37"

##### set file directories #####

# links to reference human genome, dbSNP database and temporary file directory
GENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"
TEMPDIR: "/file/path/to/tmp/"