# Specify the build of reference human genome used (either GRCh37 or GRCh38)
BUILD: "GRCh38"

##### set file directories #####

# links to reference human genome, dbSNP database and temporary file directory
GENOME: "/path/to/reference/human/genome/Homo_sapiens_assembly38.fasta"
dbSNP: "/path/to/dbSNP/All_20180418.vcf.gz"
TEMPDIR: "/file/path/to/tmp/"