# Specify the build of reference human genome used (either GRCh37 or GRCh38)
BUILD: "GRCh38"

# Specify the type of input data (either 'Single' or 'Cohort')
DATA: "Single"

# File directories to reference genome and dbSNP database
FILEDIR:
  GENOME: "/path/to/reference/human/genome/Homo_sapiens_assembly38.fasta"
  dbSNP: "/path/to/dbSNP/All_20180418.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"