# Specify the build of reference genome used (either 'GRCh37' or 'GRCh38')
BUILD: "GRCh37"

# File directories to reference genome and dbSNP database
FILEDIR:
  GENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
  dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"