# Based on: https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p slurmLogs/{rule} &&
  sbatch 
    --mail-type ALL 
    --mail-user ben.perry@agresearch.co.nz
    --parsable 
    --partition={resources.partition} 
    --gpus={resources.gpu} 
    --mem={resources.mem_mb} 
    --cpus-per-task={threads} 
    --job-name={resources.job_name} 
    --time={resources.time} 
    --output=slurmLogs/{rule}/{rule}-{wildcards}-%j.log 
    --verbose 
default-resources:
  - account=perrybe
  - partition=blade-g8-fast,inv-blade-g8,inv-bigmem-fast,inv-bigmem
  - time=20
  - mem_mb=2000
  - job_name={rule}-{wildcards}-smk
  - gpu=0
restart-times: 5
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 600
jobs: 20
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
use-conda: True
conda-frontend: mamba
use-singularity: True
reason: True
cluster-cancel: scancel
configfile: "../config/config.yaml"
