# Based on: https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p slurm_logs &&
  sbatch 
    --qos={resources.qos}
    --parsable 
    --partition={resources.partition} 
    --gpus={resources.gpu} 
    --mem="{resources.mem_gb}G"
    --cpus-per-task={threads} 
    --job-name=smk-{rule}-{wildcards}
    --time={resources.time} 
    --output=slurm_logs/{rule}-{wildcards}-%j.log 
    --verbose 
default-resources:
  - account=perrybe
  - partition=inv-iranui,inv-blade-g8,inv-bigmem-fast,inv-bigmem
  - time="02:00:00"
  - mem_gb=8
  - gpu=0
  - qos=normal
restart-times: 5
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 600
jobs: 20
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
use-conda: True
conda-frontend: mamba
use-singularity: True
reason: True
cluster-cancel: scancel
configfile: "config/config.yaml"
