##############################
###### Overall workflow ######
##############################

# Type of input data (either 'Single' or 'Cohort')
DATA: ""

# Should the pipeline be GPU accelerated where possible? (either 'Yes' or 'No')
GPU_ACCELERATED: ""

# File path to the reference genome (.fasta)
REFGENOME: ""

# File path to dbSNP database
dbSNP: ""

# Temporary file directory
TEMPDIR: ""

# Whole exome sequence settings (leave blank if analysing other data such as whole genome sequence data)
WES:
  # File path to the exome capture regions over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each region
  PADDING: ""

##############################
##### Pipeline resources #####
##############################

# Number of threads to use per rule/sample for multithreaded rules, multithreading will significantly speed up these rules (diminishing speed gains beyond 8 threads)
# Defaults to 1 thread as per config/slurm/config.yaml
#TODO Consider declaring threads at a rule level
THREADS:

# Memory requested for rules in no in mb, do not include unit with integer (e.g. 1G = 1000).
# Default memory set to 512 - see config/slurm/config.yaml
# rule level declarations for memory (resources.mem_mb) will supersede, and may be dynamic based on attempts
MAXMEMORY: ""

# Maximum number of GPU's to be used per rule/sample for gpu-accelerated runs (eg `1` for 1 GPU)
GPU:

##############################
########## Trimming ##########
##############################

# Whether or not to trim the raw fastq reads (either 'Yes' or 'No')
TRIM: ""

# If trimming, choose the adapter sequence to be trimmed (eg. `--illumina`, `--nextera` or `--small_rna`) or pass adapter sequences to the `-a` and `-a2` flags
TRIMMING:
  ADAPTERS: ""

##############################
##### Base recalibration #####
##############################

# List of resources to used for base recalibration
RECALIBRATION:
  RESOURCES:
    -
    -
    -