############################
##### Overall workflow #####
############################

# Type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"

# File directories to reference genome and dbSNP database
REFGENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each interval
  PADDING: ""